### ISSUE TITLE
Can you release the code as soon as possible

### ISSUE THREAD

**Issue by xinyunxing** [ictnlp/Auto-RAG#1]
I'm interested in your work very much, can you release the code as soon as possible,thank you very much!!!

**Comment by TianYu0313** [comment]
Thank you for your attention. We have already uploaded the trained model. For index construction, please refer to FlashRAG (we have indexed the exact page in readme). The current version of the code includes the basic logic for inference. If you have any further questions, please feel free to contact us!

**Comment by Viddesh1** [comment]
Great Work!
