### ISSUE TITLE
where is code for AUTO-RAG

### ISSUE THREAD

**Issue by Sandy4321** [ictnlp/Auto-RAG#3]
where is code for AUTO-RAG
AUTO-RAG  AUTONOMOUS RETRIEVAL-AUGMENTED GENERATION FOR LARGE LANGUAGE MODELS

**Comment by TianYu0313** [comment]
Due to some reasons, we have temporarily hidden the code. We will comment on you again when publishing to ensure that you receive timely notifications. Thank you for your attention!!

**Comment by nbhhsky-hu** [comment]
> Due to some reasons, we have temporarily hidden the code. We will comment on you again when publishing to ensure that you receive timely notifications. Thank you for your attention!!

請問一下，代碼會在本周或者本月重新發佈嗎？

**Comment by TianYu0313** [comment]
> > Due to some reasons, we have temporarily hidden the code. We will comment on you again when publishing to ensure that you receive timely notifications. Thank you for your attention!!
> 
> 請問一下，代碼會在本周或者本月重新發佈嗎？

理论上月内会发布，但我实在无法保证，也请您理解！感谢您的关注！！！

**Comment by Sandy4321** [comment]
Thanks

**Comment by TianYu0313** [comment]
Hi, we have re-released our code. Please take note.

**Comment by TianYu0313** [comment]
> Due to some reasons, we have temporarily hidden the code. We will comment on you again when publishing to ensure that you receive timely notifications. Thank you for your attention!!

Hi, we have re-released our code. Please take note.
